### ISSUE TITLE
How to get the execution method name in "OnBefore, OnAround, OnAfter,.." methods?

### ISSUE THREAD

**Issue by hoangdo86** [mingditts/AOP.net#1]
Thank you for creating such a great library, it helps me a lot.
However, I'm trying to log the excution method name in following events: "OnBefore, OnAround, OnAfter,.." but I don't know how to get the method name.
Could you please add that or show me how to do that?

Thanks
Do

**Comment by mingditts** [comment]
Hi, thank you for your feedback!
It's an interesting feature. I'm very happy to try to add this feature as soon as possible.

Feature to add:
show the class and method name (we can call it something like "SourceContext") in all the events?

Thank you!

**Comment by mingditts** [comment]
Hi, new release 1.1.1 contains this new feature.

Execution context now contains new property named "MemberName" with the name of the member of the invocation and some other properties (see commit 6c4a92c9ca31ca098d993092ef6d2d2ab93019db).

Thanks a lot for your support!
