### ISSUE TITLE
Void methods not handled correctly

### ISSUE THREAD

**Issue by rdadbhawala** [mingditts/AOP.net#2]
It appears to me that the void methods are not handled correctly.
I am using the ThrowAdvice to handle exceptions from my code.
Not only in my test, but also in your project unit tests, the Throw advice is throwing this error for a void method:
"System.NotSupportedException: 'Cannot dynamically create an instance of System.Void.'"

The Test project doesn't reveal this as an catch block without exception reference swallows this error.
https://github.com/mingditts/AOP.net/blob/6c4a92c9ca31ca098d993092ef6d2d2ab93019db/AOP.Test/BasicTest.cs#L99

The error seems to be raised from here:
https://github.com/mingditts/AOP.net/blob/6c4a92c9ca31ca098d993092ef6d2d2ab93019db/AOP/Core/AdviceProxy.cs#L344

May be void methods should be handled in a different manner.

**Comment by mingditts** [comment]
Hello and thank you for your hint. I'll fix this issue as soon as possibile!

**Comment by mingditts** [comment]
Fixed in version 1.1.2.
Thank you!

**Comment by mingditts** [comment]
Fixed in version 1.1.2.
